### ISSUE TITLE
Missing a 1.6.x branch compatible with ROCm repo manifest.

### ISSUE THREAD

**Issue by JustinTArthur** [ROCm-Developer-Tools/HIP-Examples#3]
When following the instructions at https://rocm.github.io/install.html#installing-repo the sync fails because this project doesn't have branches for the default revision in ROCm's repos manifest.

```
Fetching projects:  92% (12/13)  fatal: Couldn't find remote ref refs/heads/roc-1.6.x
error: Cannot fetch HIP-Examples

error: Exited sync due to fetch errors
```

**Comment by mangupta** [comment]
Fixed.
